import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedioskeyboardwidget/generated/GeneratedHeaderWidget25.dart';
import 'package:flutterapp/flutlabfirstapp/generatedioskeyboardwidget/generated/GeneratedIOSKeyboardLightAlphabeticWidget4.dart';
import 'package:flutterapp/flutlabfirstapp/generatedioskeyboardwidget/generated/GeneratedIOSKeyboardLightNumericWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedioskeyboardwidget/generated/GeneratedIOSKeyboardLightAlphabeticWidget10.dart';
import 'package:flutterapp/flutlabfirstapp/generatedioskeyboardwidget/generated/GeneratedIOSKeyboardLightAlphabeticWidget8.dart';

/* Frame iOS/Keyboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIOSKeyboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1699.0,
        height: 603.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 236, 236, 236),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 40.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 314.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget4(),
              ),
              Positioned(
                left: 431.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 314.0,
                child: GeneratedIOSKeyboardLightNumericWidget(),
              ),
              Positioned(
                left: 822.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 375.00018310546875,
                height: 314.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget8(),
              ),
              Positioned(
                left: 1213.000244140625,
                top: 168.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 356.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget10(),
              ),
              Positioned(
                left: 8.0,
                top: 8.0,
                right: 8.0,
                bottom: null,
                width: null,
                height: 128.0,
                child: GeneratedHeaderWidget25(),
              )
            ]),
      ),
    ));
  }
}
