import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedimageswidget3/generated/GeneratedImageBlocksWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedimageswidget3/generated/GeneratedIOSStatusBarBlackWidget20.dart';
import 'package:flutterapp/flutlabfirstapp/generatedimageswidget3/generated/GeneratedIOSBottomBar5TabsWidget14.dart';
import 'package:flutterapp/flutlabfirstapp/generatedimageswidget3/generated/GeneratedPageHeaderWidget17.dart';

/* Frame Images
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImagesWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 126.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 589.0,
                      child: GeneratedImageBlocksWidget1(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: null,
                      right: 0.0,
                      bottom: -0.5,
                      width: null,
                      height: 83.5,
                      child: GeneratedIOSBottomBar5TabsWidget14(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedIOSStatusBarBlackWidget20(),
            ),
            Positioned(
              left: 16.0,
              top: 60.0,
              right: 16.0,
              bottom: null,
              width: null,
              height: 36.0,
              child: GeneratedPageHeaderWidget17(),
            )
          ]),
    ));
  }
}
