import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget1/generated/GeneratedCalendarWidget2.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget1/generated/GeneratedIOSStatusBarWhiteWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget1/generated/GeneratedPageHeaderWidget7.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget1/generated/GeneratedIOSBottomBar5TabsWidget5.dart';

/* Frame Calendar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCalendarWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 650.0,
                child: GeneratedCalendarWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget5(),
              )
            ]),
      ),
    ));
  }
}
