import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget2/generated/GeneratedRectangle239Widget2.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget2/generated/GeneratedScrollContainerWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget2/generated/GeneratedIOSBottomBar5TabsWidget8.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget2/generated/GeneratedPageHeaderWidget10.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget2/generated/GeneratedIOSStatusBarWhiteWidget4.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget2/generated/GeneratedSegmentedControlRightWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget2/generated/GeneratedNameBioWidget2.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget2/generated/GeneratedEllipse6Widget2.dart';

/* Frame Profile/Posts
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilePostsWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: -1.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 245.0,
                      child: GeneratedRectangle239Widget2(),
                    ),
                    Positioned(
                      left: null,
                      top: 128.0,
                      right: null,
                      bottom: null,
                      width: 158.0,
                      height: 158.0,
                      child: TransformHelper.translate(
                          x: -0.50,
                          y: 0.00,
                          z: 0,
                          child: GeneratedEllipse6Widget2()),
                    ),
                    Positioned(
                      left: 52.0,
                      top: 302.0,
                      right: null,
                      bottom: null,
                      width: 272.0,
                      height: 63.0,
                      child: GeneratedNameBioWidget2(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 389.0,
                      right: 16.0,
                      bottom: null,
                      width: null,
                      height: 50.0,
                      child: GeneratedSegmentedControlRightWidget(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 455.0,
                      right: null,
                      bottom: null,
                      width: 343.0,
                      height: 256.0,
                      child: GeneratedScrollContainerWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: null,
                      right: 0.0,
                      bottom: -0.5,
                      width: null,
                      height: 83.5,
                      child: GeneratedIOSBottomBar5TabsWidget8(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedIOSStatusBarWhiteWidget4(),
            ),
            Positioned(
              left: 16.0,
              top: 60.0,
              right: 16.0,
              bottom: null,
              width: null,
              height: 36.0,
              child: GeneratedPageHeaderWidget10(),
            )
          ]),
    ));
  }
}
