import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedimageswidget1/generated/GeneratedIOSStatusBarBlackWidget19.dart';
import 'package:flutterapp/flutlabfirstapp/generatedimageswidget1/generated/GeneratedIOSBottomBar5TabsWidget13.dart';
import 'package:flutterapp/flutlabfirstapp/generatedimageswidget1/generated/GeneratedPageHeaderWidget16.dart';
import 'package:flutterapp/flutlabfirstapp/generatedimageswidget1/generated/GeneratedImageBlocksWidget.dart';

/* Frame Images
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImagesWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget19(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget16(),
              ),
              Positioned(
                left: 16.0,
                top: 126.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 844.0,
                child: GeneratedImageBlocksWidget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget13(),
              )
            ]),
      ),
    ));
  }
}
