import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget3/generated/GeneratedMessageSendWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget3/generated/GeneratedIOSBottomBar5TabsWidget10.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget3/generated/GeneratedMessageReceiveWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget3/generated/GeneratedMessageReceiveWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget3/generated/GeneratedInputSearchWidget4.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget3/generated/GeneratedIOSStatusBarBlackWidget14.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget3/generated/GeneratedMessageSendWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget3/generated/GeneratedPageHeaderWidget12.dart';

/* Frame Market
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMarketWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget14(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget12(),
              ),
              Positioned(
                left: 14.0,
                top: null,
                right: 18.0,
                bottom: 16.0,
                width: null,
                height: 50.0,
                child: GeneratedInputSearchWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget10(),
              ),
              Positioned(
                left: 16.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 126.0,
                child: GeneratedMessageReceiveWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 474.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 126.0,
                child: GeneratedMessageReceiveWidget1(),
              ),
              Positioned(
                left: null,
                top: 270.0,
                right: 19.0,
                bottom: null,
                width: 235.0,
                height: 86.0,
                child: GeneratedMessageSendWidget(),
              ),
              Positioned(
                left: null,
                top: 372.0,
                right: 18.0,
                bottom: null,
                width: 235.0,
                height: 86.0,
                child: GeneratedMessageSendWidget1(),
              )
            ]),
      ),
    ));
  }
}
