import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcoverwidget1/generated/GeneratedGroup1Widget.dart';

/* Frame Cover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCoverWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 800.0,
        height: 600.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 232, 232, 232),
                ),
              ),
              Positioned(
                left: -167.77590942382812,
                top: -88.05792236328125,
                right: null,
                bottom: null,
                width: 941.344482421875,
                height: 964.1217041015625,
                child: GeneratedGroup1Widget(),
              )
            ]),
      ),
    ));
  }
}
