import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedbottomdrawerwidget1/generated/GeneratedBGWidget103.dart';
import 'package:flutterapp/flutlabfirstapp/generatedbottomdrawerwidget1/generated/GeneratedHeaderElementsWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedbottomdrawerwidget1/generated/GeneratedActionsWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedbottomdrawerwidget1/generated/GeneratedTextWidget3.dart';

/* Frame Bottom Drawer
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBottomDrawerWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 295.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 295.0,
              child: GeneratedBGWidget103(),
            ),
            Positioned(
              left: 24.0,
              top: 170.0,
              right: null,
              bottom: null,
              width: 327.0,
              height: 86.0,
              child: GeneratedActionsWidget1(),
            ),
            Positioned(
              left: 32.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 311.0,
              height: 102.0,
              child: GeneratedTextWidget3(),
            ),
            Positioned(
              left: 172.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 32.0,
              height: 4.0,
              child: GeneratedHeaderElementsWidget1(),
            )
          ]),
    ));
  }
}
