import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcomposewidget/generated/GeneratedButtonPrimaryWidget6.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcomposewidget/generated/GeneratedIOSStatusBarBlackWidget18.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcomposewidget/generated/GeneratedComposeyourmessagehereWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcomposewidget/generated/GeneratedPageHeaderWidget15.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcomposewidget/generated/GeneratedIOSKeyboardLightAlphabeticWidget2.dart';

/* Frame Compose
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComposeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget18(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget15(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: null,
                bottom: null,
                width: 239.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -252.50,
                    z: 0,
                    child: GeneratedComposeyourmessagehereWidget()),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 307.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget6(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 0.0,
                width: 375.0,
                height: 291.0,
                child: GeneratedIOSKeyboardLightAlphabeticWidget2(),
              )
            ]),
      ),
    ));
  }
}
