import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedContentContentBlockSmallWidget4.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedRectangle239Widget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedContentContentBlockSmallWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedIOSBottomBar5TabsWidget6.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedContentContentBlockSmallWidget7.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedNameBioWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedIOSStatusBarWhiteWidget2.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedPageHeaderWidget8.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedContentContentBlockSmallWidget5.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget/generated/GeneratedSegmentedControlLeftWidget.dart';

/* Frame Profile/Posts
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilePostsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 245.0,
                child: GeneratedRectangle239Widget(),
              ),
              Positioned(
                left: null,
                top: 128.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 158.0,
                child: TransformHelper.translate(
                    x: -0.50, y: 0.00, z: 0, child: GeneratedEllipse6Widget()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget8(),
              ),
              Positioned(
                left: 52.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 63.0,
                child: GeneratedNameBioWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 389.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedSegmentedControlLeftWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 455.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 548.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 641.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 734.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget6(),
              )
            ]),
      ),
    ));
  }
}
