import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedblogpostwidget/generated/GeneratedIOSBottomBar5TabsWidget4.dart';
import 'package:flutterapp/flutlabfirstapp/generatedblogpostwidget/generated/GeneratedIOSStatusBarBlackWidget7.dart';
import 'package:flutterapp/flutlabfirstapp/generatedblogpostwidget/generated/GeneratedPostTitleTextWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedblogpostwidget/generated/GeneratedImageBlockWidget.dart';

/* Frame Blog Post
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBlogPostWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 196.0,
                child: GeneratedImageBlockWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 304.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 1117.0,
                child: GeneratedPostTitleTextWidget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget4(),
              )
            ]),
      ),
    ));
  }
}
