import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcontentwidget3/generated/GeneratedHeaderWidget28.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcontentwidget3/generated/GeneratedContentContentBlockSmallWidget15.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcontentwidget3/generated/GeneratedMessageReceiveWidget2.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcontentwidget3/generated/GeneratedContentSearchResultWidget6.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcontentwidget3/generated/GeneratedContentMarketBlockWidget19.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcontentwidget3/generated/GeneratedContentContentBlockSmallWidget12.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcontentwidget3/generated/GeneratedContentContentBlockLargeWidget8.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcontentwidget3/generated/GeneratedMessageSendWidget2.dart';

/* Frame Content
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedContentWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1012.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1122.0,
                      height: 1012.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 236, 236, 236),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 100.0000228881836,
                              child:
                                  GeneratedContentContentBlockSmallWidget12(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 100.0000228881836,
                              child:
                                  GeneratedContentContentBlockSmallWidget15(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 449.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 56.0,
                              child: GeneratedContentSearchResultWidget6(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 284.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 373.0,
                              child: GeneratedContentContentBlockLargeWidget8(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 8.0,
                              right: 8.0,
                              bottom: null,
                              width: null,
                              height: 128.0,
                              child: GeneratedHeaderWidget28(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 673.0,
                              right: null,
                              bottom: null,
                              width: 124.0,
                              height: 215.0,
                              child: GeneratedContentMarketBlockWidget19(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 149.0,
                              child: GeneratedMessageReceiveWidget2(),
                            ),
                            Positioned(
                              left: 682.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 235.0,
                              height: 109.0,
                              child: GeneratedMessageSendWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
