import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedPageHeaderWidget9.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedContentContentBlockSmallWidget10.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedIOSBottomBar5TabsWidget7.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedNameBioWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedSegmentedControlLeftWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedContentContentBlockSmallWidget9.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedContentContentBlockSmallWidget8.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedEllipse6Widget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedIOSStatusBarWhiteWidget3.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedContentContentBlockSmallWidget11.dart';
import 'package:flutterapp/flutlabfirstapp/generatedprofilepostswidget1/generated/GeneratedRectangle239Widget1.dart';

/* Frame Profile/Posts
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilePostsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 245.0,
                child: GeneratedRectangle239Widget1(),
              ),
              Positioned(
                left: null,
                top: 128.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 158.0,
                child: TransformHelper.translate(
                    x: -0.50, y: 0.00, z: 0, child: GeneratedEllipse6Widget1()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget9(),
              ),
              Positioned(
                left: 52.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 63.0,
                child: GeneratedNameBioWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 389.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedSegmentedControlLeftWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 455.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget8(),
              ),
              Positioned(
                left: 16.0,
                top: 548.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget9(),
              ),
              Positioned(
                left: 16.0,
                top: 641.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget10(),
              ),
              Positioned(
                left: 16.0,
                top: 734.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget7(),
              )
            ]),
      ),
    ));
  }
}
