import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedheaderprototypingwidget/generated/GeneratedPrototypeExamplesWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedheaderprototypingwidget/generated/GeneratedDividerLineWidget13.dart';

/* Group Header/Prototyping
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHeaderPrototypingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 4470.0,
      height: 45.000389099121094,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(0.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0003907798381987959,
              right: null,
              bottom: null,
              width: 4470.0,
              height: 1.0,
              child: GeneratedDividerLineWidget13(),
            ),
            Positioned(
              left: 0.0,
              top: 16.000391006469727,
              right: null,
              bottom: null,
              width: 232.0,
              height: 31.0,
              child: GeneratedPrototypeExamplesWidget(),
            )
          ]),
    ));
  }
}
