import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generateddatawidget/generated/GeneratedDataBarChartBackgroundWidget16.dart';
import 'package:flutterapp/flutlabfirstapp/generateddatawidget/generated/GeneratedDataMobileGraphWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generateddatawidget/generated/GeneratedHeaderWidget29.dart';
import 'package:flutterapp/flutlabfirstapp/generateddatawidget/generated/GeneratedDataBarChartFillWidget16.dart';
import 'package:flutterapp/flutlabfirstapp/generateddatawidget/generated/GeneratedContentSearchResultWidget9.dart';

/* Frame Data
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDataWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1012.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1122.0,
                      height: 1012.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 1.0,
                          color: Color.fromARGB(255, 236, 236, 236),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 254.0,
                              child: GeneratedDataMobileGraphWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 438.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 55.0,
                              child: GeneratedDataBarChartFillWidget16(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 438.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 266.0,
                              child: GeneratedDataBarChartBackgroundWidget16(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 8.0,
                              right: 8.0,
                              bottom: null,
                              width: null,
                              height: 128.0,
                              child: GeneratedHeaderWidget29(),
                            ),
                            Positioned(
                              left: 415.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 58.0,
                              child: GeneratedContentSearchResultWidget9(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
