import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedContentSearchResultWidget3.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedContentSearchResultWidget2.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedContentSearchResultWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedContentSearchResultWidget5.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedIOSBottomBar5TabsWidget3.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedPageHeaderWidget5.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedInputSearchWidget3.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedContentSearchResultWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedIOSStatusBarBlackWidget6.dart';
import 'package:flutterapp/flutlabfirstapp/generatedsearchwidget3/generated/GeneratedContentSearchResultWidget4.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 128.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputSearchWidget3(),
              ),
              Positioned(
                left: 33.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 33.0,
                child: GeneratedContentSearchResultWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 33.0,
                child: GeneratedContentSearchResultWidget1(),
              ),
              Positioned(
                left: 33.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 33.0,
                child: GeneratedContentSearchResultWidget2(),
              ),
              Positioned(
                left: 33.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 33.0,
                child: GeneratedContentSearchResultWidget3(),
              ),
              Positioned(
                left: 33.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 33.0,
                child: GeneratedContentSearchResultWidget4(),
              ),
              Positioned(
                left: 33.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 33.0,
                child: GeneratedContentSearchResultWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget3(),
              )
            ]),
      ),
    ));
  }
}
