import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget1/generated/GeneratedPageHeaderWidget4.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget1/generated/GeneratedIOSBottomBar5TabsWidget2.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget1/generated/GeneratedInputSearchWidget2.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget1/generated/GeneratedSectionHotDealsWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget1/generated/GeneratedIOSStatusBarBlackWidget4.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget1/generated/GeneratedSectionTrendingWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedmarketwidget1/generated/GeneratedSectionDealsWidget.dart';

/* Frame Market
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMarketWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 128.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputSearchWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 488.0,
                height: 222.0,
                child: GeneratedSectionHotDealsWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 488.0,
                height: 222.0,
                child: GeneratedSectionTrendingWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 718.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 222.0,
                child: GeneratedSectionDealsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget2(),
              )
            ]),
      ),
    ));
  }
}
