import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedButtonPrimaryWidget4.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedRadioSelectedWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedIOSStatusBarBlackWidget16.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedPageHeaderWidget13.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedIOSBottomBar5TabsWidget11.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedRadioUnselectedWidget2.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedRadioSelectedWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedRadioUnselectedWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedRadioUnselectedWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedradioswidget1/generated/GeneratedRadioSelectedWidget2.dart';

/* Frame Radios
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRadiosWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget16(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget11(),
              ),
              Positioned(
                left: 16.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRadioSelectedWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRadioUnselectedWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 224.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRadioSelectedWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRadioUnselectedWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRadioUnselectedWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 48.0,
                child: GeneratedRadioSelectedWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 99.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget4(),
              )
            ]),
      ),
    ));
  }
}
