import 'package:flutter/material.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget3/generated/GeneratedBackgroundWidget41.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget3/generated/GeneratedSectionHotDealsWidget1.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget3/generated/GeneratedIOSStatusBarWhiteWidget8.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget3/generated/GeneratedVideoCardWidget.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget3/generated/GeneratedIOSBottomBar5TabsWidget16.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget3/generated/GeneratedPageHeaderWidget19.dart';
import 'package:flutterapp/flutlabfirstapp/generatedcalendarwidget3/generated/GeneratedSectionTrendingWidget1.dart';

/* Frame Calendar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCalendarWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 360.0,
                child: GeneratedBackgroundWidget41(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget8(),
              ),
              Positioned(
                left: 16.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 200.0,
                child: GeneratedVideoCardWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 488.0,
                height: 222.0,
                child: GeneratedSectionHotDealsWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 488.0,
                height: 222.0,
                child: GeneratedSectionTrendingWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget19(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: -0.5,
                width: null,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget16(),
              )
            ]),
      ),
    ));
  }
}
